### ISSUE TITLE
Toggle Feature for Creators for the "Interested in updating mods" popup

### ISSUE THREAD

**Issue by MizoreYukii** [Llama-Logic/PlumbBuddy#11]
Can't remember the exact wording but this is for the "Interested in updating mods" popup right after a major game patch that's meant to take users to a Discord with mod update channels. It would be nice to have this as a toggle (at least for creators), similar to the folder checks, and have it set to off for Creators by default.

**Comment by BigBadBleuCheese** [comment]
In **Settings**, looks like this. **Onboarding** has a similar presentation.
![image](https://github.com/user-attachments/assets/6f2e28aa-342f-4c1d-b43f-012bc0679b5a)

**Onboarding** does this during user type selection, so by default on new installations, Casuals only.
```csharp
Settings.OfferPatchDayModUpdatesHelp = value is UserType.Casual;
```

However, Update Manager does this, which means in updated installations, only Creators will have it automatically turned off.
```csharp
if (lastVersion is { Major: < 1 } or { Major: 1, Minor: < 1 } && settings.Type is UserType.Creator)
{
    settings.OfferPatchDayModUpdatesHelp = false;
    superSnacks.OfferRefreshments(new MarkupString("My offer to help you with mod patch day updates is now optional, but since you've a self-identified as a Mod Creator, I have turned it off by default."), Severity.Info, options =>
    {
        options.Icon = MaterialDesignIcons.Normal.NewBox;
        options.Action = "Turn It On";
        options.ActionColor = MudBlazor.Color.Success;
        options.Onclick = _ =>
        {
            settings.OfferPatchDayModUpdatesHelp = true;
            return Task.CompletedTask;
        };
        options.RequireInteraction = true;
    });
}
```
