### ISSUE TITLE
Limit of the number of scan issues to mention in a notification

### ISSUE THREAD

**Issue by BigBadBleuCheese** [Llama-Logic/PlumbBuddy#2]
Exacerbated by #1 but still, no matter how many scan issues PB has, it should never be popping off *this* much.
![image](https://github.com/user-attachments/assets/2742afda-6370-4155-984d-3870b130a15f)

Curious about what @amethystlilac thinks should be the limiting factor here.

**Comment by amethystlilac** [comment]
If it's possible to say something like 'I found a ZIP file: x.zip and others,' I'd say limit to one per scan type. Otherwise, maybe 6 or so? Enough to encourage people to check, but not enough to take up your whole screen and still run out of space.

**Comment by BigBadBleuCheese** [comment]
> If it's possible to say something like 'I found a ZIP file: x.zip and others,' I'd say limit to one per scan type. Otherwise, maybe 6 or so? Enough to encourage people to check, but not enough to take up your whole screen and still run out of space.

Looking at your screenshot, what I'm thinking is:
* If the number of issues is three or less, list them.
* Otherwise, list the first two and a count of how many are left.

My reasoning here is that it seems like that would fit in the notification. I'd really prefer to avoid truncating.

**Comment by amethystlilac** [comment]
That's reasonable. Users would know that there are multiple issues, but the notification was so big that if I didn't know what I was doing to cause it, it would have been overwhelming instead of funny.

**Comment by BigBadBleuCheese** [comment]
What do you think?
![image](https://github.com/user-attachments/assets/b97de69d-f250-4d10-995f-d4fa45cd2475)

**Comment by amethystlilac** [comment]
Looks good. Not too big but still makes it clear there are multiple issues
